version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nba_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ingestor:
    build: ./services/ingestor
    volumes:
      - logs:/app/logs
    depends_on:
      - postgres
      - rabbitmq
volumes:
  rabbitmq_data:
    driver: local
  postgres_data:
    driver: local
  logs:
    external: true